# Generated by Django 5.0.7 on 2024-08-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'دسته بندی کالا',
                'verbose_name_plural': 'دسته بندی های کالا ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ProductsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productscategory')),
            ],
            options={
                'verbose_name': 'دسته بندی ثانویه سرویس',
                'verbose_name_plural': 'دسته بندی های ثانویه ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ProductsSubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productssubcategory')),
            ],
            options={
                'verbose_name': 'دسته بندی ثالثیه کالا',
                'verbose_name_plural': 'دسته بندی های ثالثیه کالا ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=True, verbose_name='عرضه کننده / تقاضا کننده')),
                ('is_legal', models.BooleanField(default=True, verbose_name='حقوقی / حقیقی')),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='گواهینامه ها')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='نام کالا')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر')),
                ('slug', models.SlugField(allow_unicode=True, null=True)),
                ('consumed', models.CharField(max_length=8000, null=True, verbose_name='مورد مصرف')),
                ('performance', models.TextField(null=True, verbose_name='عملکرد')),
                ('constituents', models.CharField(max_length=8000, null=True, verbose_name='اهم اجزای تشکیل دهنده')),
                ('analytical_material', models.CharField(max_length=8000, null=True, verbose_name='مواد آنالیز')),
                ('description', models.TextField(null=True, verbose_name='شرح کالا')),
                ('color', models.CharField(blank=True, choices=[('white', 'سفید'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('red', 'قرمز'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('blue', 'آبی'), ('green', 'سبز'), ('brown', 'قهوه ای'), ('black', 'مشکی'), ('gray', 'طوسی'), ('golden', 'طلایی'), ('silver', 'نقره ای')], max_length=50, null=True, verbose_name='رنگ')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='ظرفیت')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purchaseprice', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='قیمت خرید')),
                ('sellingprice', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='قیمت فروش')),
                ('manufacturers', models.CharField(max_length=5000, null=True, verbose_name='تولیدکنندگان')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_products', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('category', models.ManyToManyField(blank=True, to='products.productscategory', verbose_name='دسته بندی کالا')),
                ('subcategory', models.ManyToManyField(blank=True, to='products.productssubcategory', verbose_name='دسته بندی ')),
                ('subsubcategory', models.ManyToManyField(blank=True, to='products.productssubsubcategory', verbose_name='دسته بندی 2 ')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
    ]
