# Generated by Django 5.0.7 on 2024-09-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='services.servicescategory')),
            ],
            options={
                'verbose_name': 'دسته بندی خدمات',
                'verbose_name_plural': 'دسته بندی های خدمات ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userstatus', models.CharField(choices=[('تقاضا کننده', 'تقاضا کننده'), ('عرضه کننده', 'عرضه کننده')], default='تقاضا کننده', max_length=50)),
                ('title', models.CharField(max_length=30, null=True, verbose_name='نام خدمات')),
                ('slug', models.SlugField(allow_unicode=True, null=True)),
                ('description', models.TextField(null=True, verbose_name='شرح خدمات')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='ظرفیت')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='قیمت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_services', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('category', models.ManyToManyField(blank=True, to='services.servicescategory', verbose_name='گروه تخصص')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
