# Generated by Django 5.0.7 on 2024-08-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'دسته بندی سرویس',
                'verbose_name_plural': 'دسته بندی های سرویس ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ServicesSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicescategory')),
            ],
            options={
                'verbose_name': 'دسته بندی ثانویه سرویس',
                'verbose_name_plural': 'دسته بندی های ثانویه سرویس ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ServicesSubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicessubcategory')),
            ],
            options={
                'verbose_name': 'دسته بندی ثالثیه سرویس',
                'verbose_name_plural': 'دسته بندی های ثالثیه سرویس ',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=True, verbose_name='عرضه کننده / تقاضا کننده')),
                ('is_legal', models.BooleanField(default=True, verbose_name='حقوقی / حقیقی')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='دانش فنی')),
                ('description', models.TextField(null=True, verbose_name='توضیحات اضافه')),
                ('slug', models.SlugField(allow_unicode=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='گواهینامه')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='قیمت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_services', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('category', models.ManyToManyField(blank=True, to='services.servicescategory', verbose_name='گروه تخصص')),
                ('subcategory', models.ManyToManyField(blank=True, to='services.servicessubcategory', verbose_name='گروه ')),
                ('subsubcategory', models.ManyToManyField(blank=True, to='services.servicessubsubcategory', verbose_name='2گروه ')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
